language: python

python:
  - 3.5

install:
  - pip install -rrequirements-test.txt
  - pip install tox-travis
  - pip install coveralls
  - pip install flake8

before_script:
  - flake8 --max-line-length=120 .

script:
  - tox

after_success:
  - coveralls